---
title: "Lightning Talk Stats"
author: "Naomi Lubkin"
date: "11/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(patchwork)
library(car)
library(performance)
library(DHARMa)
library(fitdistrplus)
library(gamlss)
library(tidyverse)
```

```{r}
polyp_data <-read.csv("Jelly data - Polyps.csv")
ephyra_data <-read.csv("Jelly data - Ephyra.csv")
```

```{r}
# fixing ephyra data
ephyra_clean <- ephyra_data %>%
  rename(collection_day = "Data.collection.day",
         jar_code = "Jar.Code..ex..E1.",
         num_pulsations = "Number.of.pulsations", 
         radius = "Radius", 
         treatment = "Chemical") %>%
  mutate(jar_code = as.factor(jar_code)) %>%
  dplyr::select(collection_day, jar_code, treatment, num_pulsations, radius) %>%
  na.omit()

# fixing polyp data
polyp_clean <- polyp_data %>%
  rename(collection_day = 'Data.collection.day', 
         jar_code = 'Jar.Code..ex..E1.', 
         treatment = Chemical, 
         num_elongated = 'Elongation.', 
         num_ruffled = 'Ruffled.', 
         num_asexual_buds = 'Asexual.Repro.', 
         total_num = Total) %>%
  mutate(prop_elongated = num_elongated/total_num + 0.001, 
         prop_ruffled = num_ruffled/total_num + 0.001, 
         prop_buds = num_asexual_buds/total_num + 0.001,
         jar_code = as.factor(jar_code))  %>%
  dplyr::select(collection_day, jar_code, treatment, num_elongated, prop_elongated, num_ruffled, prop_ruffled, num_asexual_buds, prop_buds, total_num) 

```

```{r}
# making an initial 4 part graph to peek at the polyp response variable data
elongation_per_day = 
  ggplot(polyp_clean, aes(x=collection_day, y=num_elongated)) +
         geom_point() +
        geom_smooth(se=FALSE)
ruffles_per_day = 
  ggplot(polyp_clean, aes(x=collection_day, y=num_ruffled)) +
         geom_point() +
        geom_smooth(se=FALSE)
asexual_buds_per_day = 
  ggplot(polyp_clean, aes(x=collection_day, y=num_asexual_buds)) +
         geom_point() +
        geom_smooth(se=FALSE)
total_num = 
  ggplot(polyp_clean, aes(x=collection_day, y=total_num)) +
         geom_point() +
        geom_smooth(se=FALSE)

(elongation_per_day | ruffles_per_day)/(asexual_buds_per_day | total_num)
```
```{r}
prop_elongation_per_day = 
  ggplot(polyp_clean, aes(x=collection_day, y=prop_elongated)) +
         geom_point() +
        geom_smooth(se=FALSE)
prop_ruffles_per_day = 
  ggplot(polyp_clean, aes(x=collection_day, y=prop_ruffled)) +
         geom_point() +
        geom_smooth(se=FALSE)
prop_buds_per_day = 
  ggplot(polyp_clean, aes(x=collection_day, y=prop_buds)) +
         geom_point() +
        geom_smooth(se=FALSE)



(prop_elongation_per_day | prop_ruffles_per_day |prop_buds_per_day)
```


```{r}
# initial graph of ephyra data to see what it looks like
ggplot(ephyra_clean, aes(x=collection_day, y=radius, colour=treatment)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE)
```


```{r}
ggplot(ephyra_clean, aes(x=collection_day, y=num_pulsations, colour=treatment))+
  geom_point() +
  geom_smooth(se=FALSE)
```

```{r}
# initial graph of polyp data to see what it looks like
ggplot(polyp_clean, aes(x=collection_day, y=prop_ruffled, colour=treatment))+
  geom_point() +
  geom_smooth(method=lm,  se=FALSE)
```


# polyps

From Sara:: 

1. calculate proportions for each response variable 

2. assess distributions (check out T08) 
```{r}
# fitting distributions for data

# elongation: logit normal (AIC = -11.99)
fitDist(prop_elongated, data = polyp_clean, type = "real0to1", try.gamlss = T)

# ruffled: logit normal (AIC = -14.40)
fitDist(prop_ruffled, data = polyp_clean, type = "real0to1", try.gamlss = T)

# buds: Generalized Beta Type 2 (AIC = -55.22)
b_BE <- histDist(polyp_clean$prop_buds, "GB1", density = T)
b_BE2 <- histDist(polyp_clean$prop_buds, "GB2", density = T)
fitDist(prop_buds, data = polyp_clean, type = "real0to1", try.gamlss = T)
descdist(polyp_clean$prop_buds)

b_lNO <- histDist(polyp_clean$prop_buds, "LOGNO", density = T)
b_GA <- histDist(polyp_clean$prop_buds, "GA", density = T)
b_WEI <- histDist(polyp_clean$prop_buds, "WEI", density = T)
GAIC(b_lNO, b_GA, b_WEI, b_BE, b_BE2)

# total: delaporte (AIC = 318.28)
fitDist(total_num, data = polyp_clean, type = "counts", try.gamlss = T)

```

3. using response distributions, choose model function - gamma or poisson is prob glm, bino neg binom is probably gamlss 
```{r}
# creating the models
# Elongation: Logit Normal (LOGITNO)
mod_elongation <- gamlss(prop_elongated ~ treatment*collection_day 
                         + re(random = ~1 | jar_code), 
                         family = LOGITNO(), 
                         data = polyp_clean, 
                         control = gamlss.control(n.cyc = 60))
histDist(polyp_clean$prop_elongated, 
         "LOGITNO", 
         density = T, 
         main = "Logit Normal")
summary(mod_elongation)
# p-value = 0.104, so not significant

# Ruffled: Logit Normal (LOGITNO)
mod_ruffled <- gamlss(prop_ruffled ~ treatment*collection_day 
                      + re(random = ~1 | jar_code), 
                      family = LOGITNO(), 
                      data = polyp_clean, 
                      control = gamlss.control(n.cyc = 50))
histDist(polyp_clean$prop_ruffled, 
         "LOGITNO", 
         density = T, 
         main = "Logit Normal")
summary(mod_ruffled)
# p-value = 0.0413, so significant!

# Buds: Generalized Beta Type 2 (GB2)
mod_buds <- gamlss(prop_buds ~ treatment*collection_day 
                   + random(jar_code), 
                   family = GB2(), 
                   data = polyp_clean, 
                   method = CG(), 
                   control = gamlss.control(n.cyc = 50))
histDist(polyp_clean$prop_buds, 
         "GB2", 
         density = T, 
         main = "Generalized Beta Type 2")
summary(mod_buds)
# p-value = 0.138, so not significant

# Total: Delaporte (DEL)
mod_total <- gamlss(total_num ~ treatment*collection_day 
                    + re(random = ~1 | jar_code), 
                    family = DEL(), 
                    data = polyp_clean, 
                    control = gamlss.control(n.cyc = 60))
histDist(polyp_clean$total_num,
         "DEL", 
         density = T, 
         main = "Delaporte")
summary(mod_total)
# p-value = 0.998, so not significant

```

# ephyra
```{r}
# fitting distributions for data

# radius: Generalized Poisson (AIC = 2390.01)
fitDist(radius, data = ephyra_clean, type = "counts", try.gamlss = T)

# pulsations: Zero Inflated Negative Binomial type I (AIC = 1483.84)
fitDist(num_pulsations, data = ephyra_clean, type = "counts", try.gamlss = T)
```

```{r}
# creating the models
# Radius: Generalized Poisson (GPO)
mod_total <- gamlss(radius ~ treatment*collection_day 
                    + re(random = ~1 | jar_code), 
                    family = GPO(), 
                    data = ephyra_clean, 
                    control = gamlss.control(n.cyc = 60))
histDist(ephyra_clean$radius,
         "GPO", 
         density = T, 
         main = "Generalized Poisson")
summary(mod_total)
# p-value < 2e-16, so it is significant!

# Pulsations: Zero Inflated Negative Binomial type I (ZINBI)
mod_total <- gamlss(num_pulsations ~ treatment*collection_day 
                    + re(random = ~1 | jar_code), 
                    family = ZINBI(), 
                    data = ephyra_clean, 
                    control = gamlss.control(n.cyc = 60))
histDist(ephyra_clean$radius,
         "ZINBI", 
         density = T, 
         main = " Zero Inflated Negative Binomial type I")
summary(mod_total)
# p-value < 2e-16, so it is significant!

```

