---
title: "Ruffled Analyses"
author: "Mara Bohm"
date: "10/12/2021"
output: pdf_document
---

```{r}
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=70), tidy=TRUE)
# code above ensures no text is cut off when knit
```

# Loading in Packages and Data

```{r, results=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(patchwork)
library(car)
library(performance)
library(DHARMa)
library(fitdistrplus)
library(gamlss)
library(tidyverse)

polyp_data <- read_csv("/Users/marabohm/Github/Jelly-Data/data/ds2021_polyp_data.csv")
```


# Cleaning the Data

```{r, results=FALSE, message=FALSE, warning=FALSE}

polyp_clean <- polyp_data %>%
  rename(collection_day = 'Data collection day', 
         jar_code = 'Jar Code (ex. E1)', 
         treatment = Chemical, 
         num_elongated = 'Elongation?', 
         num_ruffled = 'Ruffled?', 
         num_asexual_buds = 'Asexual Repro?', 
         total_num = Total) %>%
  mutate(jar_code = as.factor(jar_code),
         treatment = as.factor(treatment), 
         treatment = fct_relevel(treatment, 
                                 "Control", 
                                 "Caffeine", 
                                 "Estradiol", 
                                 "Combo"))  %>%
  dplyr::select(collection_day, 
                jar_code, 
                treatment, 
                num_elongated, 
                num_ruffled, 
                num_asexual_buds, 
                total_num) 

```


# Fitting Distributions for Ruffled Data

```{r, results=FALSE, message=FALSE, warning=FALSE}

fitDist(num_ruffled, 
        data = polyp_clean, 
        type = "counts", 
        try.gamlss = T)
# best fit: Negative Binomial type II (AIC = 444.109)

# model was having difficulty converging with NBII, so tried some other fits:

descdist(polyp_clean$num_ruffled)
# Cullen and Frey plot indicates Lognormal, Gamma and Weibull distributions may be a good fit, so we compare to each other using Generalized AIC:

b_NB2 <- histDist(polyp_clean$num_ruffled, 
                  "NBII", 
                  density = T)
b_lNO <- histDist(polyp_clean$num_ruffled, 
                  "LOGNO", 
                  density = T)
b_GA <- histDist(polyp_clean$num_ruffled, 
                 "GA", 
                 density = T)
b_WEI <- histDist(polyp_clean$num_ruffled, 
                  "WEI", 
                  density = T)
GAIC(b_lNO,
     b_GA, 
     b_WEI, 
     b_NB2)
# best fit: Weibull Distribution (AIC = 442.8371)

```


# Creating The Ruffled Model

```{r, results=FALSE, message=FALSE, warning=FALSE}

mod_countwtotal_ruffled <- gamlss(num_ruffled ~ treatment*collection_day 
                      + re(random = ~1 | jar_code)
                      + re(random = ~1 | total_num), 
                      family = WEI(), 
                      data = polyp_clean, 
                      control = gamlss.control(n.cyc = 60))

```

```{r, message=FALSE, warning=FALSE}
histDist(polyp_clean$num_ruffled, 
         "WEI", 
         density = T, 
         main = "Count Polyp Ruffling Compared to Weibull Distribution",
         xlab = "Number Ruffled")

# summarizing the model to determine p-values:
summary(mod_countwtotal_ruffled)

```