---
title: "Figures"
author: "Naomi Lubkin"
date: "11/28/2021"
output: pdf_document
---
```{r}
#getting correlation coefficients for the figures
#Figure 1
```

###Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#loading in libraries
library(patchwork)
library(tidyverse)
library(viridis)
library(ggplot2)

#loading in the data
polyp_data <-read.csv("Jelly data - Polyps.csv")


# fixing polyp data
polyp_clean <- polyp_data %>%
  rename(collection_day = 'Data.collection.day', 
         jar_code = 'Jar.Code..ex..E1.', 
         treatment = Chemical, 
         num_elongated = 'Elongation.', 
         num_ruffled = 'Ruffled.', 
         num_asexual_buds = 'Asexual.Repro.', 
         total_num = Total, 
         time_in_days = days_after) %>%
  mutate(prop_elongated = num_elongated/total_num + 0.001, 
         prop_ruffled = num_ruffled/total_num + 0.001, 
         prop_buds = num_asexual_buds/total_num + 0.001,
         jar_code = as.factor(jar_code),
         treatment = as.factor(treatment), 
         treatment = fct_relevel(treatment, "Control", "Caffeine", "Estradiol", "Combination")) %>%
  dplyr::select(collection_day, jar_code, treatment, num_elongated, prop_elongated, num_ruffled, prop_ruffled, num_asexual_buds, prop_buds, total_num, time_in_days) 

#making data frames with just Caffeine, Combination, Estradiol, and Control
#treatments for later plots and analyses 

#data frame with combination and control
just_combo <- polyp_clean %>%
  filter(treatment == "Combination" | treatment == "Control")

#data frame with caffeine and control
just_caf <- polyp_clean %>%
  filter(treatment == "Caffeine" | treatment == "Control")

#data frame with caffeine, combination, and control
just_caf_combo <- polyp_clean %>%
  filter(treatment == "Combination" | treatment == "Control" | treatment == "Caffeine")

#data frame with only estradiol
only_est <- polyp_clean %>%
  filter(treatment == "Estradiol")

#data frame with only caffeine
only_caf <- polyp_clean %>%
  filter(treatment == "Caffeine")

#data frame with only combination
only_combo <- polyp_clean %>%
  filter(treatment == "Combination")

#data frame with only control
only_control <- polyp_clean %>%
  filter(treatment == "Control")

```

##Figures

### Figure 1: Response variables over time
```{r}
#the number of ruffled polyps over time
ruffles_time <- ggplot(polyp_clean, aes(x=time_in_days,  y=num_ruffled)) +
  geom_point(colour="#fb9b06") +
  geom_smooth(method = "lm", se=FALSE, colour="black", show.legend=FALSE) +
  labs(x = "Time (days)", y = "Number of Ruffled Polyps") +
  scale_x_continuous(breaks=c(0, 3, 6, 9, 12)) +
  theme_classic() +
    theme(legend.position = "none") +
  ggtitle("A. Ruffling") 
##Spearman's rank correlation coefficient for the correlation between the number
#of ruffled polyps and time
cor(polyp_clean$time_in_days,polyp_clean$num_ruffled, method= "spearman")
#r= 0.910

#the number of elongated polyps over time
elo_time <- ggplot(polyp_clean, aes(x=time_in_days,  y=num_elongated)) +
  geom_point(colour="#e55c30") +
  geom_smooth(method = "lm", se=FALSE, colour="black", show.legend=FALSE) +
  labs(x = "Time (days)", y = "Number of Elongated Polyps") +
  scale_x_continuous(breaks=c(0, 3, 6, 9, 12)) +
  theme_classic() +
    theme(legend.position = "none") +
  ggtitle("B. Elongation") 
##Spearman's rank correlation coefficient for the correlation between the number
#of elongated polyps and time
cor(polyp_clean$time_in_days,polyp_clean$num_elongated, method= "spearman")
#r= 0.830

#The number of asexual buds over time
buds_time <- ggplot(polyp_clean, aes(x=time_in_days,  y=num_asexual_buds)) +
  geom_point(colour="#450a69") +
  geom_smooth(method = "lm", se=FALSE, colour="black", show.legend=FALSE) +
  labs(x = "Time (days)", y = "Number of Asexual Buds") +
  scale_x_continuous(breaks=c(0, 3, 6, 9, 12)) +
  theme_classic() +
    theme(legend.position = "none") +
  ggtitle("C. Budding") 
#Spearman's rank correlation coefficient for the correlation between number of 
#asexual buds and time 
cor(polyp_clean$time_in_days,polyp_clean$num_asexual_buds, method= "spearman")
#r= 0.845


#The total number of polyps over time
total_time <- ggplot(polyp_clean, aes(x=time_in_days,  y=total_num)) +
  geom_point(colour="#b1325a") +
  geom_smooth(method = "lm", se=FALSE, colour="black", show.legend=FALSE) +
  labs(x = "Time (days)", y = "Total Number of Polyps") +
  scale_x_continuous(breaks=c(0, 3, 6, 9, 12))+
  theme_classic() +
    theme(legend.position = "none") +
  ggtitle("D. Total Number") 
#Spearman's rank correlation coefficient for the correlation between total number 
#of polyps and time 
cor(polyp_clean$time_in_days,polyp_clean$total_num, method= "spearman")
#r= 0.899


#The above figures put together into one image using patchwork
(ruffles_time | elo_time)/(buds_time | total_time)

```

### Figure 2: Ruffling in each treatment
```{r}
#box plot for caffeine, and combination, and control groups with time 
#as a factor
box_caf_combo<- ggplot(just_caf_combo, aes(  x = as.factor(time_in_days), y = num_ruffled, fill=treatment))+
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = c("#404788FF", "#238A8DFF","#55C667FF")) +
  labs(x = "Time (days)", y = "Number of Ruffled Polyps", fill ="Treatment") 
box_caf_combo
```


### Figure 3: Elongation per treatment and over time
```{r}
#scatter/line plot of the number of elongated polyps over time, per treatment
plot_elongation <- ggplot(polyp_clean, aes(x=time_in_days, y=num_elongated, colour=treatment, shape = treatment))+
  geom_point(aes(x=time_in_days, y=num_elongated, colour=treatment, shape = treatment)) +
  theme_classic() +
  geom_smooth(se=FALSE, method="lm") +
  labs(x = "Time (days)", y = "Number of Elongated Polyps", colour ="Treatment", shape = NULL) +
  scale_colour_manual(name = "Treatment", labels= c("Control", "Caffeine", "Estradiol", "Combination"), values = c("#404788FF", "#238A8DFF",  "#FDE725FF","#55C667FF")) +
  scale_shape_manual(name = "Treatment", labels= c("Control", "Caffeine", "Estradiol", "Combination"), values = c(15,19,17,8)) +
  scale_x_continuous(breaks=c(0, 3, 6, 9, 12)) +
  ggtitle("B")


#Spearman's rank correlation coefficient for the correlation between number of elongated polyps and time in each treatment 
#control: 
cor(only_control$time_in_days,only_control$num_elongated, method= "spearman")
#r= 0.745

#caffeine: 
cor(only_caf$time_in_days,only_caf$num_elongated, method= "spearman")
#r=0.823

#estradiol: 
cor(only_est$time_in_days,only_est$num_elongated, method= "spearman")
#r=0.914

#combination: 
cor(only_combo$time_in_days,only_combo$num_elongated, method= "spearman")
#r=0.927




#box plot of elongation per treatment overall
box_elongation <- ggplot(polyp_clean, aes(x=treatment, y=num_elongated, fill = treatment)) +
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = c("#404788FF", "#238A8DFF", "#FDE725FF","#55C667FF")) +
  labs(x = "Treatment", y = "Number of Elongated Polyps") +
  theme(legend.position = "none", axis.text.x = element_text(angle=30, vjust = 0.8, hjust = 0.7)) +
  ggtitle("A")
box_elongation
  
#using patchwork to put the above plots together into one image
(box_elongation | plot_elongation)
```

### Budding
```{r}
#box plot with just control and combination treatments for number of asexual 
#buds overall
box_buds <-ggplot(just_combo, aes(x=treatment, y=num_asexual_buds, fill = treatment)) +
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = c("#404788FF", "#55C667FF")) +
  labs(x = "Treatment", y = "Number of Asexual Buds") +
  theme(legend.position = "none")  +
   ggtitle("A")
 
 #scatter/line plot of just combination and control treatments over time for 
#number of asexual buds over time 
plot_buds <- ggplot(just_combo, aes(x=time_in_days, y=num_asexual_buds, colour=treatment, shape = treatment)) +
  geom_point() +
  theme_classic() +
   labs(x = "Time (days)", y = "Number of Asexual Buds", colour ="Treatment") +
  geom_smooth(se= FALSE, method="lm")+
   scale_colour_manual(name = "Treatment", labels= c("Control", "Combination"), values = c("#404788FF", "#55C667FF")) +
  scale_shape_manual(name = "Treatment", labels= c("Control", "Combination"), values = c(15,8)) +
  scale_x_continuous(breaks=c(0, 3, 6, 9, 12)) +
  ggtitle("B")
#Spearman's rank correlation coefficient for the correlation between number of asexual buds and time in each treatment 
#control: 
cor(only_control$time_in_days, only_control$num_asexual_buds, method= "spearman")
#r= 0.917

#combination: 
cor(only_combo$time_in_days, only_combo$num_asexual_buds, method= "spearman")
#r=0.914



#using patchwork to put the above plots together into one image
 (box_buds | plot_buds)
```

### Figure 4: Total Number of Polyps
```{r}
#scatter/line plot of total number of polyps over time, broken up by treatment
plot_total <- ggplot(polyp_clean, aes(x=time_in_days, y=total_num, colour=treatment, shape = treatment))+
  geom_point(aes(colour=treatment)) +
  theme_classic() +
  geom_smooth(se=FALSE, method="lm") +
  labs(x = "Time (days)", y = "Total Number of Polyps", colour ="Treatment") +
  scale_colour_manual(name = "Treatment", labels= c("Control", "Caffeine", "Estradiol", "Combination"), values = c("#404788FF", "#238A8DFF",  "#FDE725FF","#55C667FF")) +
  scale_shape_manual(name = "Treatment", labels= c("Control", "Caffeine", "Estradiol", "Combination"), values = c(15,19,17,8)) +
  scale_x_continuous(breaks=c(0, 3, 6, 9, 12)) +
  ggtitle("B")

#Spearman's rank correlation coefficient for the correlation between total number of polyps and time in each treatment 
#control: 
cor(only_control$time_in_days,only_control$total_num, method= "spearman")
#r= 0.960

#caffeine: 
cor(only_caf$time_in_days,only_caf$total_num, method= "spearman")
#r=0.954

#estradiol: 
cor(only_est$time_in_days,only_est$total_num, method= "spearman")
#r=0.906

#combination: 
cor(only_combo$time_in_days,only_combo$total_num, method= "spearman")
#r=0.917




#box plot for total number of polyps, by treatment, overall
box_total <- ggplot(polyp_clean, aes(x=treatment, y=total_num, fill = treatment)) +
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = c("#404788FF", "#238A8DFF", "#FDE725FF","#55C667FF")) +
  labs(x = "Treatment", y = "Total Number of  Polyps") +
  theme(legend.position = "none", axis.text.x = element_text(angle=30, vjust = 0.8, hjust = 0.7)) + 
  ggtitle("A")
  
#using patchwork to put the above plots together into one image
(box_total | plot_total)
```

