---
title: "Proportion Analyses"
author: "Mara Bohm"
date: "23/11/2021"
output: pdf_document
---


# initial setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(patchwork)
library(car)
library(performance)
library(DHARMa)
library(fitdistrplus)
library(gamlss)
library(tidyverse)

polyp_data <-read.csv("Jelly data - Polyps.csv")
```


# fixing polyp data

```{r}

polyp_clean <- polyp_data %>%
  rename(collection_day = 'Data.collection.day', 
         jar_code = 'Jar.Code..ex..E1.', 
         treatment = Chemical, 
         num_elongated = 'Elongation.', 
         num_ruffled = 'Ruffled.', 
         num_asexual_buds = 'Asexual.Repro.', 
         total_num = Total) %>%
  mutate(prop_elongated = num_elongated/total_num + 0.001, 
         prop_ruffled = num_ruffled/total_num + 0.001, 
         prop_buds = num_asexual_buds/total_num + 0.001,
         jar_code = as.factor(jar_code),
         treatment = as.factor(treatment), 
         treatment = fct_relevel(treatment, "Control", "Caffeine", "Estradiol", "Combo"))  %>%
  dplyr::select(collection_day, jar_code, treatment, num_elongated, prop_elongated, num_ruffled, prop_ruffled, num_asexual_buds, prop_buds, total_num) 

```


## fitting distributions for data

```{r}

# elongation: logit normal (AIC = -15.3908)
fitDist(prop_elongated, data = polyp_clean, type = "real0to1", try.gamlss = T)

# ruffled: logit normal (AIC = -24.7355)
fitDist(prop_ruffled, data = polyp_clean, type = "real0to1", try.gamlss = T)

# buds: Generalized Beta Type 2 (AIC = -43.64892)
b_BE <- histDist(polyp_clean$prop_buds, "GB1", density = T)
b_BE2 <- histDist(polyp_clean$prop_buds, "GB2", density = T)
fitDist(prop_buds, data = polyp_clean, type = "real0to1", try.gamlss = T)
descdist(polyp_clean$prop_buds)

b_lNO <- histDist(polyp_clean$prop_buds, "LOGNO", density = T)
b_GA <- histDist(polyp_clean$prop_buds, "GA", density = T)
b_WEI <- histDist(polyp_clean$prop_buds, "WEI", density = T)
GAIC(b_lNO, b_GA, b_WEI, b_BE, b_BE2)

# total: delaporte (AIC = 436.754)
fitDist(total_num, data = polyp_clean, type = "counts", try.gamlss = T)

```


## creating the models

```{r}
# Elongation: Logit Normal (LOGITNO)
mod_elongation <- gamlss(prop_elongated ~ treatment*collection_day 
                         + re(random = ~1 | jar_code), 
                         family = LOGITNO(), 
                         data = polyp_clean, 
                         control = gamlss.control(n.cyc = 60))
histDist(polyp_clean$prop_elongated, 
         "LOGITNO", 
         density = T, 
         main = "Proportional Polyp Elongation Compared to Logit Normal Distibution",
         xlab = "Proportion Elongated")
summary(mod_elongation)
# p-value = 0.00514, so significant!

# Ruffled: Logit Normal (LOGITNO)
mod_ruffled <- gamlss(prop_ruffled ~ treatment*collection_day 
                      + re(random = ~1 | jar_code), 
                      family = LOGITNO(), 
                      data = polyp_clean, 
                      control = gamlss.control(n.cyc = 50))
histDist(polyp_clean$prop_ruffled, 
         "LOGITNO", 
         density = T, 
         main = "Proportional Polyp Ruffling Compared to Logit Normal Distibution",
         xlab = "Proportion Ruffled")
summary(mod_ruffled)
# p-value = 0.00423, so significant!

# Buds: Generalized Beta Type 2 (GB2)
mod_buds <- gamlss(prop_buds ~ treatment*collection_day 
                   + re(random = ~1 | jar_code), 
                   family = GB2(), 
                   data = polyp_clean, 
                   method = CG(), 
                   control = gamlss.control(n.cyc = 250))
histDist(polyp_clean$prop_buds, 
         "GB2", 
         density = T, 
         main = "Proportional Polyp Budding Compared to Generalized Beta 2 Distibution",
         xlab = "Proportion Budding")
summary(mod_buds)
# p-value = 0.000805, so significant!

# Total: Delaporte (DEL)
mod_total <- gamlss(total_num ~ treatment*collection_day 
                    + re(random = ~1 | jar_code), 
                    family = DEL(), 
                    data = polyp_clean, 
                    control = gamlss.control(n.cyc = 60))
histDist(polyp_clean$total_num,
         "DEL", 
         density = T, 
         main = "Count Polyp Total Compared to Delaporte Distribution",
         xlab = "Number Polyps Total")
summary(mod_total)
# p-value = 2.33e-0.8, so significant!

```

# Summary of Proportional Data:
Elongation p-value = 0.00514, so significant!
Ruffled p-value = 0.00423, so significant!
Buds p-value = 0.000805, so significant!
Total (count data) p-value = 2.33e-0.8, so significant!
