---
title: "Figures"
author: "Naomi Lubkin"
date: "11/24/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(patchwork)
library(tidyverse)
library(viridis)

#loading in the data
polyp_data <-read.csv("Analyses/Jelly data - Polyps.csv")


# fixing polyp data
polyp_clean <- polyp_data %>%
  rename(collection_day = 'Data.collection.day', 
         jar_code = 'Jar.Code..ex..E1.', 
         treatment = Chemical, 
         num_elongated = 'Elongation.', 
         num_ruffled = 'Ruffled.', 
         num_asexual_buds = 'Asexual.Repro.', 
         total_num = Total, 
         time_in_days = days_after) %>%
  mutate(prop_elongated = num_elongated/total_num + 0.001, 
         prop_ruffled = num_ruffled/total_num + 0.001, 
         prop_buds = num_asexual_buds/total_num + 0.001,
         jar_code = as.factor(jar_code),
         treatment = as.factor(treatment), 
         treatment = fct_relevel(treatment, "Control", "Caffeine", "Estradiol", "Combo")) %>%
  dplyr::select(collection_day, jar_code, treatment, num_elongated, prop_elongated, num_ruffled, prop_ruffled, num_asexual_buds, prop_buds, total_num, time_in_days) 

#calculating the average value for each variable on each day, by treatment (ex. avg number of elongated polyps in control treatment on day 3). for plots later. 
#Standard deviations also  calculated
averages <- polyp_clean %>%
  dplyr::select(treatment, time_in_days, num_elongated, num_ruffled, num_asexual_buds, total_num) %>%
  group_by(treatment, time_in_days) %>% 
  mutate(avg_ruffled = mean(num_ruffled),
         sd_ruffled = sd(num_ruffled), 
         avg_elongated = mean(num_elongated),
         sd_elongated = sd(num_ruffled),
         avg_buds = mean(num_asexual_buds),
         sd_buds =sd(num_asexual_buds),
         avg_total = mean(total_num), 
         sd_total = sd(total_num))

```

## Figures 
```{r}
#RUFFLES FIGURE
#figure for elongation
ruffles_plot <- ggplot(averages, aes(x=time_in_days, y=avg_ruffled, colour=treatment))+
  geom_point() +
  geom_line() +
  theme_classic() +
  #geom_errorbar(aes(ymin= avg_ruffled-sd_ruffled, ymax=avg_ruffled+sd_ruffled, width=0.1, colour=treatment)) +
  labs(x = "Time (days)", y = "Number of Ruffled Polyps", colour ="Treatment") +
  xlim(0, 12)

ruffles_plot

#ELONGATION FIGURE
elongation_plot <- ggplot(averages, aes(x=time_in_days, y=avg_elongated, colour=treatment)) +

  
elongation_plot  
#BUDS FIGURE
buds_plot <- ggplot(averages, aes(x=time_in_days, y=avg_elongated, colour=treatment)) +
  
buds_plot
#TOTAL NUMBER FIGURE
total_plot <- ggplot(averages, aes(x=time_in_days, y=avg_total, colour=treatment)) +

total_plot

```


